/* =============================================================================
   PURPOSE  : SQL plan baselines and profiles - the mechanisms that pin or
              nudge execution plans. Check here when a plan refuses to change,
              or refuses to stay changed.
   VIEWS    : dba_sql_plan_baselines, dba_sql_profiles
   LICENSE  : SQL Plan Management (baselines) is included in Enterprise
              Edition. SQL PROFILES are generated by the SQL Tuning Advisor,
              which REQUIRES the Tuning Pack - query 2 only reports what
              exists, but creating profiles is a licensed activity.
   RAC      : N/A - dictionary views. Baselines are database-wide and apply on
              every instance.
   PARAMS   : None
   NOTES    : ENABLED + ACCEPTED is what actually gets used. A baseline that is
              accepted but not enabled does nothing.
              FIXED = YES means the optimizer will not evolve past it - useful
              to lock a known-good plan, but it also blocks genuinely better
              plans from ever being adopted, so review fixed baselines
              periodically.
              REPRODUCED = NO means the optimizer could not reproduce the
              stored plan, usually because an index was dropped. Those
              baselines are silently doing nothing.
              Pairs with previous-plans.sql: find the good plan_hash_value
              there, then pin it here.
   ============================================================================= */

col sql_handle for a24
col plan_name for a32
col sql_text for a45 word_wrapped
col origin for a20

/* -----------------------------------------------------------------------
   QUERY 1: Plan baselines
   ----------------------------------------------------------------------- */
SELECT
    sql_handle,
    plan_name,
    origin,
    enabled,
    accepted,
    fixed,
    reproduced,
    autopurge,
    created,
    last_executed,
    DBMS_LOB.SUBSTR(sql_text, 120, 1) AS sql_text
FROM
    dba_sql_plan_baselines
ORDER BY
    created DESC;


/* -----------------------------------------------------------------------
   QUERY 2: SQL profiles
   ----------------------------------------------------------------------- */
SELECT
    name,
    category,
    status,
    type,
    force_matching,
    created,
    last_modified
FROM
    dba_sql_profiles
ORDER BY
    created DESC;
